// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq6OB5-idNGqHkMogUf_HCbJglilUJIVg',
    appId: '1:736412566489:web:cf1a53e3dcf85426164fc8',
    messagingSenderId: '736412566489',
    projectId: 'activite3avance-a257e',
    authDomain: 'activite3avance-a257e.firebaseapp.com',
    storageBucket: 'activite3avance-a257e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ZqgSPzL_qfv67yzCubuh5mtvTG9jQ3k',
    appId: '1:736412566489:android:35ffb3714f6bd1cf164fc8',
    messagingSenderId: '736412566489',
    projectId: 'activite3avance-a257e',
    storageBucket: 'activite3avance-a257e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADnVjkkazuS-33g6Hkawh4yzZFYRhemAM',
    appId: '1:736412566489:ios:03f19b4ba9088375164fc8',
    messagingSenderId: '736412566489',
    projectId: 'activite3avance-a257e',
    storageBucket: 'activite3avance-a257e.firebasestorage.app',
    iosBundleId: 'com.example.activite3avance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADnVjkkazuS-33g6Hkawh4yzZFYRhemAM',
    appId: '1:736412566489:ios:03f19b4ba9088375164fc8',
    messagingSenderId: '736412566489',
    projectId: 'activite3avance-a257e',
    storageBucket: 'activite3avance-a257e.firebasestorage.app',
    iosBundleId: 'com.example.activite3avance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq6OB5-idNGqHkMogUf_HCbJglilUJIVg',
    appId: '1:736412566489:web:09d8ef4b6c9e4139164fc8',
    messagingSenderId: '736412566489',
    projectId: 'activite3avance-a257e',
    authDomain: 'activite3avance-a257e.firebaseapp.com',
    storageBucket: 'activite3avance-a257e.firebasestorage.app',
  );
}
